# Generated by Django 5.0.6 on 2024-06-20 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DndCombatDefense',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DndCastingSpeed',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DndClass',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DndComponent',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DndDamageType',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DndElement',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('general_desc', models.TextField()),
                ('trait_desc', models.TextField()),
                ('combat_desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DndMasteryLevel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DndAbility',
            fields=[
                ('dndcombatdefense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.dndcombatdefense')),
            ],
            options={
                'abstract': False,
            },
            bases=('forms.dndcombatdefense',),
        ),
        migrations.CreateModel(
            name='DndSkill',
            fields=[
                ('dndcombatdefense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.dndcombatdefense')),
            ],
            options={
                'abstract': False,
            },
            bases=('forms.dndcombatdefense',),
        ),
        migrations.CreateModel(
            name='DndDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.dndelement')),
            ],
            options={
                'unique_together': {('name', 'element')},
            },
        ),
        migrations.CreateModel(
            name='DndForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('has_higher_level_bonus', models.BooleanField()),
                ('higher_levels', models.TextField(blank=True)),
                ('concentration', models.BooleanField()),
                ('target', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('costs_slot', models.BooleanField()),
                ('special_reqs', models.TextField(blank=True, null=True)),
                ('casting_speed', models.ManyToManyField(to='forms.dndcastingspeed')),
                ('classes', models.ManyToManyField(to='forms.dndclass')),
                ('discipline', models.ManyToManyField(to='forms.dnddiscipline')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.dndelement')),
                ('saving_throws', models.ManyToManyField(to='forms.dndcombatdefense')),
                ('mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.dndmasterylevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DndRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('num_dice', models.IntegerField()),
                ('num_sides', models.IntegerField()),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.dnddamagetype')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.dndform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
